name: Build and Release luci-app-5GSmartCase (SDK)

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up OpenWrt SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev wget
        # 下载 Mediatek Filogic 架构的 SDK (23.05 版本)
        SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/mediatek/filogic/openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
        wget $SDK_URL
        mkdir openwrt
        tar xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt
        # 设置环境变量
        echo "SDK_PATH=$PWD/openwrt" >> $GITHUB_ENV
        
    - name: Prepare plugin
      run: |
        mkdir -p $SDK_PATH/package/luci-app-5GSmartCase
        cp -r luasrc $SDK_PATH/package/luci-app-5GSmartCase/
        cp -r root $SDK_PATH/package/luci-app-5GSmartCase/
        cp Makefile $SDK_PATH/package/luci-app-5GSmartCase/
        # 确保 feeds 已更新
        $SDK_PATH/scripts/feeds update -a
        $SDK_PATH/scripts/feeds install -a
        
    - name: Build package
      run: |
        cd $SDK_PATH
        # 生成默认配置
        cat > .config <<EOF
        CONFIG_TARGET_mediatek=y
        CONFIG_TARGET_mediatek_filogic=y
        CONFIG_PACKAGE_luci-app-5GSmartCase=y
        EOF
        make defconfig
        # 编译插件 (失败时显示详细日志)
        make package/luci-app-5GSmartCase/compile -j$(nproc) || make package/luci-app-5GSmartCase/compile V=s
        
    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find $SDK_PATH/bin -name "luci-app-5GSmartCase*.ipk" -exec cp {} artifacts/ \;
        # 同时收集依赖包
        find $SDK_PATH/bin -name "luci-i18n-*-zh-cn*.ipk" -exec cp {} artifacts/ \;
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ipk-packages
        path: artifacts/
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ipk-packages
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          OpenWrt 23.05 插件包 (Mediatek Filogic 架构)
          包含:
          - luci-app-5GSmartCase 主程序
          - 中文语言包 (如存在)
        files: |
          *.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
